### PR TITLE
Bump versions

### PR DESCRIPTION
**Pull request by rsevilla87**
## Type of change

- [ ] Refactor
- [ ] New feature
- [ ] Bug fix
- [x] Optimization
- [ ] Documentation Update

## Changelog

**Kube-burner-ocp**
* Removing Dev ES instance reference by @vishnuchalla in https://github.com/kube-burner/kube-burner-ocp/pull/116
* Subset of metadata fields by @rsevilla87 in https://github.com/kube-burner/kube-burner-ocp/pull/113
* add PostRun for workloads by @venkataanil in https://github.com/kube-burner/kube-burner-ocp/pull/115
* * Remove kubeproxy and OVNK service sync latency metrics by @rsevilla87 in https://github.com/kube-burner/kube-burner-ocp/pull/109
* Custom metric-profile list from flag by @rsevilla87 in https://github.com/kube-burner/kube-burner-ocp/pull/111

---

**k8s-netperf**

* Use NodeSystemInfo rather than node labels by @rsevilla87 in https://github.com/cloud-bulldozer/k8s-netperf/pull/152
* fix: missing burst in csv header by @rsicart in https://github.com/cloud-bulldozer/k8s-netperf/pull/153

### CODE REVIEW

**Comment by vishnuchalla** [comment]
Once this is merged, can we update the v2.2.5 release that already has some of these changes please? A PR at prow is open as well: https://github.com/openshift/release/pull/57560

**Review by krishvoor — APPROVED** [review]
/lgtm

**Pull request merged**
