### PR TITLE
Updates the WORKLOAD condition

### PR DESCRIPTION
**Pull request by krishvoor**
This PR would bypass updating iterations if the WORKLOAD is udn-density-l3-pods

## Type of change

- [x] Refactor
- [x] New feature
- [ ] Bug fix
- [ ] Optimization
- [ ] Documentation Update

## Description

Adds `udn-density-l3-pods` to WORKLOAD Logic

## Related Tickets & Documents

- Related Issue #
- Closes #

## Checklist before requesting a review

- [ ] I have performed a self-review of my code.
- [ ] If it is a core feature, I have added thorough tests.

## Testing
- Please describe the System Under Test.
- Please provide detailed steps to perform tests related to this code change.
- How were the fix/results from this change verified? Please provide relevant screenshots or results.

### CODE REVIEW

**Comment by krishvoor** [comment]
Works CI Job: https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_release/57161/rehearse-57161-pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-aws-4.18-nightly-x86-udn-density-l3-pods-24nodes/1841666847351508992

**Review by venkataanil — APPROVED** [review]
LGTM

**Pull request merged**
