### PR TITLE
Use snappy as data backup alternative

### PR DESCRIPTION
**Pull request by amitsagtani97**
Created a separate script for data backup through snappy.

### CODE REVIEW

**Comment by Harshith-umesh** [comment]
Can one of the admins verify this patch?

**Comment by chaitanyaenr** [comment]
Like we discussed on the slack, we need to consume/integrate snappy with the workloads/utils in the e2e-benchmarking to move any data points of interest especially the prometheus dump through https://github.com/cloud-bulldozer/e2e-benchmarking/tree/master/utils/scale-ci-diagnosis.

**Review by mohit-sheth — APPROVED** [review]
LGTM

**Review by chaitanyaenr — APPROVED** [review]
LGTM

**Pull request merged**
