### PR TITLE
Fix hypershift conditionals

### PR DESCRIPTION
**Pull request by rsevilla87**
Signed-off-by: Raul Sevilla <rsevilla@redhat.com>

### Description

These two conditionals are incorrect and are always evaluated true

### CODE REVIEW

**Comment by qiliRedHat** [comment]
@rsevilla87 I tested with your fork/branch, still have some problem
```
10-27 19:46:40.338  [1mThu Oct 27 11:46:33 UTC 2022 Disabling cluster version operator[0m
10-27 19:46:40.338  deployment.apps/cluster-version-operator scaled
10-27 19:46:40.338  common.sh: line 74: !false: command not found
10-27 19:46:40.338  [1mThu Oct 27 11:46:33 UTC 2022 Using the default ingress-operator image[0m
10-27 19:46:40.338  [1mThu Oct 27 11:46:33 UTC 2022 Using the default router image[0m
10-27 19:46:40.338  [1mThu Oct 27 11:46:33 UTC 2022 Scaling ingress-operator down to 0[0m
10-27 19:46:40.338  Error from server (NotFound): deployments.apps "ingress-operator" not found
```

**Comment by rsevilla87** [comment]
> @rsevilla87 I tested with your fork/branch, still have some problem
> 
> ```
> 10-27 19:46:40.338  �[1mThu Oct 27 11:46:33 UTC 2022 Disabling cluster version operator�[0m
> 10-27 19:46:40.338  deployment.apps/cluster-version-operator scaled
> 10-27 19:46:40.338  common.sh: line 74: !false: command not found
> 10-27 19:46:40.338  �[1mThu Oct 27 11:46:33 UTC 2022 Using the default ingress-operator image�[0m
> 10-27 19:46:40.338  �[1mThu Oct 27 11:46:33 UTC 2022 Using the default router image�[0m
> 10-27 19:46:40.338  �[1mThu Oct 27 11:46:33 UTC 2022 Scaling ingress-operator down to 0�[0m
> 10-27 19:46:40.338  Error from server (NotFound): deployments.apps "ingress-operator" not found
> ```

ok, as discussed in Slack, you can try again with the latest bits

**Review by smalleni — APPROVED** [review]
Looks like bash behaves weirdly with booleans :-)

**Review by mukrishn — APPROVED** [review]

**Comment by qiliRedHat** [comment]
I tested with the merged code, it worked well now.

**Pull request merged**
