### PR TITLE
Enable targeted log forwarding

### PR DESCRIPTION
**Pull request by chaitanyaenr**
This commit adds support to the logging workload to forward logs from the
specified services - infra, applications and audit to the Elasticsearch
backend. Application logs are forwarded by default.

### CODE REVIEW

**Review by dry923 — APPROVED** [review]
LGTM!

**Comment by dry923** [comment]
@chaitanyaenr Trying to deploy this in my env and it looks like it fails b/c these vars aren't set. Can we get them defaulted in the env.sh file?
```
FLUENTD_MEMORY_LIMITS
FLUENTD_CPU_REQUESTS
FLUENTD_MEMORY_REQUESTS
```

**Review by dry923 — APPROVED** [review]
LGTM!

**Comment by dry923** [comment]
@chaitanyaenr So copying the note from slack here. In the current config there is no way for us to query the ES that gets stood up from outside of Kibana. We need to be able to do this for the logging tests so we can verify all the messages were received. Here is a way to do it from the thread I linked.
```
To perform a query from your local machine to the elasticsearch that is running on the cluster you will have to do the following steps:
• Copy admin-cert and admin-key from the running ES container to your local machine. Here is an example:
oc cp elasticsearch-cdm-ehq89vdw-1-7c6dfb6c67-fk2rs:/etc/elasticsearch/secret/admin-cert ~/es-secret/admin-cert
and
oc cp elasticsearch-cdm-ehq89vdw-1-7c6dfb6c67-fk2rs:/etc/elasticsearch/secret/admin-key ~/es-secret/admin-key
• Run port-forward to access remote ES port:
oc port-forward elasticsearch-cdm-ehq89vdw-1-7c6dfb6c67-fk2rs 9200:9200
• Then use these admin-cert and admin-key to perform requests or to connect to this service via ES Golang API. Here is an example with curl:
curl -s -k --cert ~/es-secret/admin-cert --key ~/es-secret/admin-key https://localhost:9200/_cat/indices
Result:
green open app-000001   HSOGJXtaTAqdg5sempPc7w 1 0      0 0    261b    261b
green open audit-000001 uQPvTFTfRXKXQJmXYIMnQg 1 0      0 0    261b    261b
green open .security    UiyfNiMPR1-epd1DSiBcrg 1 0      5 0  29.1kb  29.1kb
green open .kibana_1    MI0zc373QWm7Rx99uwum7A 1 0      0 0    261b    261b
green open infra-000001 niOivnwhRsWkzNP-gOzK5Q 1 0 279796 0 158.9mb 158.9mb
```

**Comment by dry923** [comment]
> @chaitanyaenr So copying the note from slack here. In the current config there is no way for us to query the ES that gets stood up from outside of Kibana. We need to be able to do this for the logging tests so we can verify all the messages were received. Here is a way to do it from the thread I linked.
> 
> ```
> To perform a query from your local machine to the elasticsearch that is running on the cluster you will have to do the following steps:
> • Copy admin-cert and admin-key from the running ES container to your local machine. Here is an example:
> oc cp elasticsearch-cdm-ehq89vdw-1-7c6dfb6c67-fk2rs:/etc/elasticsearch/secret/admin-cert ~/es-secret/admin-cert
> and
> oc cp elasticsearch-cdm-ehq89vdw-1-7c6dfb6c67-fk2rs:/etc/elasticsearch/secret/admin-key ~/es-secret/admin-key
> • Run port-forward to access remote ES port:
> oc port-forward elasticsearch-cdm-ehq89vdw-1-7c6dfb6c67-fk2rs 9200:9200
> • Then use these admin-cert and admin-key to perform requests or to connect to this service via ES Golang API. Here is an example with curl:
> curl -s -k --cert ~/es-secret/admin-cert --key ~/es-secret/admin-key https://localhost:9200/_cat/indices
> Result:
> green open app-000001   HSOGJXtaTAqdg5sempPc7w 1 0      0 0    261b    261b
> green open audit-000001 uQPvTFTfRXKXQJmXYIMnQg 1 0      0 0    261b    261b
> green open .security    UiyfNiMPR1-epd1DSiBcrg 1 0      5 0  29.1kb  29.1kb
> green open .kibana_1    MI0zc373QWm7Rx99uwum7A 1 0      0 0    261b    261b
> green open infra-000001 niOivnwhRsWkzNP-gOzK5Q 1 0 279796 0 158.9mb 158.9mb
> ```

So a little more fine grain example of this w/ creating a service to attach to:
```
oc create svc clusterip elasticsearch-log-test --tcp=9200
```
edit the elasticsearch-log-test service to change the label selector to 
```
  selector:
    cluster-name: elasticsearch
```
create passthrough route
```
oc create route passthrough --service=elasticsearch-log-test elasticsearch-log-test
```

**Review by dry923 — APPROVED** [review]
Tested this and LGTM! Great work Ravi!

**Review by rsevilla87 — APPROVED** [review]
LGTM!

**Pull request merged**
