### PR TITLE
Combine metric profiles

### PR DESCRIPTION
**Pull request by rsevilla87**
### Description

Combine metrics-aggregated.yaml and metrics.yaml files.

I managed to combine them thanks to expressions such as:
```
irate(process_cpu_seconds_total{service="kubelet",job="kubelet"}[2m]) * 100 and on (node) topk(3,avg_over_time(irate(process_cpu_seconds_total{service="kubelet",job="kubelet"}[2m])[{{ .elapsed }}:]) and on (node) kube_node_role{role="worker"})
```

Which uses the [magic variable {{ .elapsed }}](https://kube-burner.readthedocs.io/en/latest/metrics/#using-the-elapsed-variable) which takes the value of the benchmark duration. Now, in large-scale deployments we won't collect metrics for all worker nodes (which is overkill) but instead we'll collect metrics for the 3 worker nodes with more kubelet CPU usage, same for other similar metrics.

### CODE REVIEW

**Comment by Harshith-umesh** [comment]
@rsevilla87 thoughts on reviewing and updating this PR's logic https://github.com/cloud-bulldozer/e2e-benchmarking/pull/411 here?

**Review by afcollins — APPROVED** [review]

**Review by Harshith-umesh — COMMENTED** [review]
LGTM

**Comment by rsevilla87** [comment]
Let's put this one on hold, I have to make some change in the grafana report to ensure we don't loss any interesting metric

**Pull request closed without merging**
