### PR TITLE
add charts to uperf results (experimental); minor improvements

### PR DESCRIPTION
**Pull request by mohit-sheth**
Charts (experimental)

- examples: [hostnet](https://docs.google.com/spreadsheets/d/1Fb9CmTncNpVT4XlkvxYkfSZ2eBjDyZHvPtQ94hesUF8/edit#gid=1078555054) and [pod network](https://docs.google.com/spreadsheets/d/1-kCcVuW6WyayFzzMjgsVnO7OomDaI7s0sZQjUtWD07U/edit#gid=110559253)
- currently not integrated with `csv_gen.py` as  `chart.py` requires 2 inputs, spreadsheet-url and grid-id. The former can be scraped programmatically but no luck with latter as of **now**.
- works only with a set csv structure i.e [crd has to be similar to the one in e2e-benchmarking](https://github.com/cloud-bulldozer/e2e-benchmarking/blob/master/workloads/network-perf/ripsaw-uperf-crd.yaml). So it will work for Pipeline in the future
- added uuids to the sheet for uperf and router
- the header also shows network type used in addition to platform and cluster version

### CODE REVIEW

**Review by jtaleric — COMMENTED** [review]
@mohit-sheth is this ready? Or still WIP?

**Comment by mohit-sheth** [comment]
ready!

**Comment by Harshith-umesh** [comment]
Can one of the admins verify this patch?

**Review by jtaleric — APPROVED** [review]
LGTM

**Pull request merged**
