### PR TITLE
fix relative path for google spreadsheet

### PR DESCRIPTION
**Pull request by Harshith-umesh**
### Fixes
wrong path for csv_gen.py

### CODE REVIEW

**Review by sjug — CHANGES_REQUESTED** [review]
This is not the way

**Comment by sjug** [comment]
Do we still want to keep the `csv_gen` functionality in e2e?

**Comment by Harshith-umesh** [comment]
> Do we still want to keep the `csv_gen` functionality in e2e?

@sjug this is more of an immediate fix, cause router perf on airflow is failing.

**Comment by mohit-sheth** [comment]
we want e2e just to handle pushing to the gsheet part. i.e no parsing of yaml or deciding pass/fail like we used to earlier. 
This PR https://github.com/cloud-bulldozer/benchmark-comparison/pull/55 should create a csv for us from benchmark-comparison

**Review by mohit-sheth — APPROVED** [review]
LGTM

**Comment by Harshith-umesh** [comment]
> we want e2e just to handle pushing to the gsheet part. i.e no parsing of yaml or deciding pass/fail like we used to earlier. This PR [cloud-bulldozer/benchmark-comparison#55](https://github.com/cloud-bulldozer/benchmark-comparison/pull/55) should create a csv for us from benchmark-comparison

also gsheet functionality is not part of the workload code itself but handled in e2e-benchmarking/utils

**Comment by morenod** [comment]
Im not 100% happy with this solution, but I need it to let the router tests to be completed

**Review by jtaleric — COMMENTED** [review]
Huge -2 here. If I didn't have a doc appt, i would of blocked this totally.

**Comment by jtaleric** [comment]
> a) Like I mentioned this isn't the correct way to fix this IMO. b) Removing the functionality would also be an immediate fix.

ALL OF THIS. 

This needs to be removed ASAP.

**Comment by whitleykeith** [comment]
I tend to agree with @jtaleric and @sjug on this one too. 

IMO I think we should start looking at what we use the gsheet logic for and either (1) changing that logic to build visualizations from the data in ES (similar to the control plane dashboard we have for kube-burner results) or (2) adding the csv_gen logic into the report dag

**Comment by mohit-sheth** [comment]
reverting this until all of us are on the same page

**Pull request merged**
