### PR TITLE
Cert update to 2048 bit

### PR DESCRIPTION
**Pull request by skordas**
### Description
Update rsa key to 2048
### Fixes
https://issues.redhat.com/browse/OCPBUGS-5521
Current certificate was generated as 1024-bit and the caCertificate was generated as 2048-bit. Both need to be 2048 to work with FIPS

### CODE REVIEW

**Review by krishvoor — APPROVED** [review]
lgtm

**Review by chentex — APPROVED** [review]
lgtm

**Review by rsevilla87 — CHANGES_REQUESTED** [review]
Hey @skordas, thanks for the PR!

Rather than providing our own certificate to the ingress controller I think we can the default ingress certificates:

This can be done by creating an edge route w/o specifying any certificate information. i.e:

```yaml
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: {{.name}}-{{.Replica}}
spec:
  host: www.{{.name}}.example-{{.Iteration}}-{{.Replica}}.com
  to:
    kind: Service
    name: {{.name}}-{{.Iteration}}-{{.Replica}}
  tls:
    termination: edge
```

**Comment by skordas** [comment]
@rsevilla87 
Tested with default certificates:
FIPS cluster
https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/e2e-benchmarking-multibranch-pipeline/job/upgrade/482/ 
No FIPS cluster
https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/e2e-benchmarking-multibranch-pipeline/job/upgrade/483/

Both success

**Review by rsevilla87 — APPROVED** [review]
Nice, thanks for checking. LGTM

**Pull request merged**
