### PR TITLE
Add Additional tags to Hypershift Clusters

### PR DESCRIPTION
**Pull request by krishvoor**
### Description
This PR adds the following tags to the HyperShift clusters 

1) User:${GITHUB_USER}
2) {MGMT_CLUSTER_NAME}:{HOSTED_CLUSTER_NAME}

Signed-off-by: Krishna Harsha Voora <krvoora@redhat.com>

### CODE REVIEW

**Comment by krishvoor** [comment]
Hi @dry923 @morenod @mukrishn :wave: 
ptal

**Review by morenod — APPROVED** [review]
LGTM

**Comment by smalleni** [comment]
@krishvoor @mukrishn Adding User tag is useful for airflow but probably not so much for e2e. Here, folks usually run from the upstream repo itself and not the fork. So most likely, the User is always `cloud-bulldozer`. The user tag is more useful for airflow playgrounds IMO

**Comment by krishvoor** [comment]
@smalleni I hear you, the original scope of the project was to add tags. I agree the `User` tag should go into the airflow playground.

When working with e2e-benchmarking-->hypershift script, we definitely need a way to know which user spun the hosted cluster.

**Review by mukrishn — APPROVED** [review]

**Pull request merged**
