### PR TITLE
Fix benchmark comparison in uperf tests

### PR DESCRIPTION
**Pull request by Harshith-umesh**
### Description
fixes benchmark comparison in uperf 
adds new function get_gold_ocp_version to automatically get the cluster version to compare with existing ocp version
### Fixes
Fixes failing airflow uperf runs

### CODE REVIEW

**Comment by Harshith-umesh** [comment]
failing since upstream changed , need to rebase

**Review by rsevilla87 — CHANGES_REQUESTED** [review]
With the new mechanism to get the GOLD_OCP_VERSION variable we have to remove references in docs to it.

**Review by rsevilla87 — APPROVED** [review]
LGTM

**Review by mohit-sheth — APPROVED** [review]

**Pull request merged**
