### PR TITLE
Deprecate legacy kube-burner workload

### PR DESCRIPTION
**Pull request by rsevilla87**
## Type of change

- [ ] Refactor
- [ ] New feature
- [ ] Bug fix
- [x] Deprecation
- [ ] Documentation Update

## Description

The workload's on this directory shouldn't be used anymore, people should use https://github.com/cloud-bulldozer/e2e-benchmarking/tree/master/workloads/kube-burner-ocp-wrapper going forward.

## Checklist before requesting a review

- [x] I have performed a self-review of my code.
- [ ] If it is a core feature, I have added thorough tests.

### CODE REVIEW

**Comment by rsevilla87** [comment]
Please, feel free to tag more affected users.

**Comment by dry923** [comment]
@rsevilla87 Can we add an estimated removal date or something as well when the directory will be removed?

**Comment by jtaleric** [comment]
Since this change only removes the CI runs I am good with it... I do think there are teams (ACS in particular) using non-ocp-wrapper kube-burner.

**Comment by paigerube14** [comment]
Agree with Joe! Think it's ok to remove ci references. Not sure if we are fully ready (qe) side for a full removal of kube burner folder

**Comment by rsevilla87** [comment]
> Agree with Joe! Think it's ok to remove ci references. Not sure if we are fully ready (qe) side for a full removal of kube burner folder

Thanks for the feedback!, as @dry923 also suggested, we should maybe add an EOL date so we can definitively remove the `kube-burner` directory

**Pull request merged**
