### PR TITLE
Updating kube-burner-ocp wrapper to v1.2.5

### PR DESCRIPTION
**Pull request by vishnuchalla**
## Type of change

- [x] Refactor
- [x] New feature
- [ ] Bug fix
- [x] Optimization
- [ ] Documentation Update

## Description

* kube-burner changelog: https://github.com/kube-burner/kube-burner/releases/tag/v1.9.6
* kube-burner-ocp changelog: https://github.com/kube-burner/kube-burner-ocp/releases/tag/v1.2.5

## Checklist before requesting a review

- [x] I have performed a self-review of my code.
- [ ] If it is a core feature, I have added thorough tests.

## Testing
- Testing through the PR hooks.

### CODE REVIEW

**Comment by vishnuchalla** [comment]
> /test e2e-cluster-density-v2-single-node /test e2e-node-density-cni-single-node /test e2e-node-density-heavy-single-node /test e2e-node-density-single-node

cc: @svetsa-rh

**Review by rsevilla87 — APPROVED** [review]
lgtm!

**Pull request merged**
