### PR TITLE
Kube burner metrics refactor

### PR DESCRIPTION
**Pull request by rsevilla87**
### Description

Get rid of metrics not useful (or too granular) for release reporting (we should use Dittybopper or Thanos for cluster debugging and long term storage of this kind of metrics) , hence reducing the number of indexed documents. and add some of the upstream SLI metrics (https://github.com/kubernetes/community/blob/master/sig-scalability/slos/slos.md#steady-state-slisslos) such as:

- Pod Ready latency
- Network programming latency
- ReadOnly API requests
- Mutating API requests
- Etcd Fsync latency (This is a OpenShift SLI)

Dashboard refactor is also ready: http://grafana.apps.observability.perfscale.devcluster.openshift.com/d/n8_lX3-nk/kube-burner-report-v2?orgId=1&from=1644849374037&to=1644856446517&var-Datasource=Observability%20-%20ripsaw-kube-burner&var-sdn=openshift-sdn&var-job=cluster-density&var-uuid=287e8000-8677-45-cluster-density-20220214&var-master=ip-10-0-129-75.us-west-2.compute.internal&var-worker=ip-10-0-130-220.us-west-2.compute.internal&var-infra=ip-10-0-153-10.us-west-2.compute.internal&var-namespace=All&var-latencyPercentile=P99

### CODE REVIEW

**Comment by dry923** [comment]
@mukrishn FYI you might want to take a look at this re your hypershift metric list

**Comment by smalleni** [comment]
@rsevilla87 this looks good, will be updating our kube-burner dashboards to reflect these changes, then?

**Comment by smalleni** [comment]
> @rsevilla87 this looks good, will be updating our kube-burner dashboards to reflect these changes, then?

Ah, I saw the dashboard refactor in the comment as well. Thanks!

**Review by smalleni — APPROVED** [review]

**Comment by mohit-sheth** [comment]
thoughts on adding OVN row as well? similar to http://grafana.apps.observability.perfscale.devcluster.openshift.com/d/_XeYNzD7k/ocp-performance-thanos?orgId=1

**Comment by smalleni** [comment]
> thoughts on adding OVN row as well? similar to http://grafana.apps.observability.perfscale.devcluster.openshift.com/d/_XeYNzD7k/ocp-performance-thanos?orgId=1

That's a good idea although in the current form, the leader elections for sbdb/nbdb mean nothing since they proactively transfer leadership on snapshotting.

@rsevilla87 @mohit-sheth we already capture metrics (cpu and memory) for ovn pods, I think we need an ovn panel for that on the dashboard and that would be perfect.

**Review by mohit-sheth — APPROVED** [review]
LGTM

**Review by amitsagtani97 — APPROVED** [review]

**Pull request merged**
