### PR TITLE
Update netperf

### PR DESCRIPTION
**Pull request by jtaleric**
## Type of change

- [ ] Refactor
- [ ] New feature
- [x] Bug fix
- [x] Optimization
- [ ] Documentation Update

## Description

- Increase test duration from 30 to 60
- Increase number of samples from 3 to 5
- Bump to v0.1.17 for better error handling

## Related Tickets & Documents

- Related Issue #
- Closes #

## Checklist before requesting a review

- [ ] I have performed a self-review of my code.
- [ ] If it is a core feature, I have added thorough tests.

## Testing
- Please describe the System Under Test.
- Please provide detailed steps to perform tests related to this code change.
- How were the fix/results from this change verified? Please provide relevant screenshots or results.

### CODE REVIEW

**Comment by mohit-sheth** [comment]
lgtm
the default test time might be too long with this change 
we can probably skip 4096 message size and CRR to offset some of the duration gain
one can always add more message sizes and types..

**Comment by jtaleric** [comment]
I am good to drop CRR and 4096 if we don't see any additional value having these tests. I am getting a full run to advertise the amount of time this current config takes.

**Review by mukrishn — APPROVED** [review]
lgtm

**Review by mukrishn — APPROVED** [review]
lgtm

**Pull request merged**
