### PR TITLE
Bump kube-burner-ocp to [1.3.4]

### PR DESCRIPTION
**Pull request by krishvoor**
## Type of change

- [ ] Refactor
- [x] New feature
- [ ] Bug fix
- [ ] Optimization
- [ ] Documentation Update

## Description

Adds New udn-density-l3-pods workload

## Related Tickets & Documents

- Related Issue #
- Closes #

## Checklist before requesting a review

- [ ] I have performed a self-review of my code.
- [ ] If it is a core feature, I have added thorough tests.

## Testing
- Please describe the System Under Test.
- Please provide detailed steps to perform tests related to this code change.
- How were the fix/results from this change verified? Please provide relevant screenshots or results.

### CODE REVIEW

**Comment by krishvoor** [comment]
Needs 1.3.4 release from kube-burner-ocp

**Review by jtaleric — APPROVED** [review]
/lgtm

**Pull request merged**
