### PR TITLE
Update e2e version of benchmark-operator

### PR DESCRIPTION
**Pull request by whitleykeith**
Updates e2e scripts to use new ripsaw deploy commands after the operator-sdk upgrade

### CODE REVIEW

**Review by jtaleric — APPROVED** [review]
LGTM

**Comment by whitleykeith** [comment]
need this before CI works because e2e doesn't build the operator https://github.com/cloud-bulldozer/benchmark-operator/pull/609

**Review by rsevilla87 — APPROVED** [review]
lgtm

**Pull request merged**
