### PR TITLE
Update CI vars to match new naming

### PR DESCRIPTION
**Pull request by rsevilla87**
### Description

CI was broken because of this commit https://github.com/cloud-bulldozer/e2e-benchmarking/commit/bede0b6b0f1a8dceadf85cf0f888b7627d626e8b

Signed-off-by: Raul Sevilla <rsevilla@redhat.com>

### CODE REVIEW

**Review by chaitanyaenr — APPROVED** [review]
LGTM

**Review by Harshith-umesh — APPROVED** [review]

**Review by jtaleric — APPROVED** [review]
LGTM thanks for cleaning this up @rsevilla87

**Pull request merged**
