### PR TITLE
hotfix logging status check

### PR DESCRIPTION
**Pull request by whitleykeith**
fixes some conditional logic issue present in the logging workload

### CODE REVIEW

**Review by dry923 — APPROVED** [review]
LGTM!

**Review by chaitanyaenr — APPROVED** [review]
LGTM

**Comment by jtaleric** [comment]
`13:31:25 uperf-benchmark-pod-network-1                                      uperf         Starting Servers   Collecting       not connected   Not collected    6443eb5f-85b5-5eaf-bc60-ae548fe47ab2   27m`

Seems concerning these never started.

**Pull request merged**
