### PR TITLE
Dropping ingress-perf runtime

### PR DESCRIPTION
**Pull request by rsevilla87**
## Type of change

- [ ] Refactor
- [ ] New feature
- [ ] Bug fix
- [x] Optimization
- [ ] Documentation Update

## Description

We need to cut down the duration of some of our tests.

Ideally I'd like to drop it to 2m, but since it's collecting some prometheus metrics I think is better to collect couple of more datapoints (30s each) to get a better data quality.

## Related Tickets & Documents

- Related Issue #
- Closes #

## Checklist before requesting a review

- [ ] I have performed a self-review of my code.
- [ ] If it is a core feature, I have added thorough tests.

## Testing
- Please describe the System Under Test.
- Please provide detailed steps to perform tests related to this code change.
- How were the fix/results from this change verified? Please provide relevant screenshots or results.

### CODE REVIEW

**Review by krishvoor — APPROVED** [review]
/lgtm

**Comment by jtaleric** [comment]
> Ideally I'd like to drop it to 2m, but since it's collecting some prometheus metrics I think is better to collect just a couple of more datapoints (30s each) to get a better data quality.

I see you mentioned 2m but I see the runtime is now 3m? Did you mean to say reduce it by 2m?

**Comment by rsevilla87** [comment]
> > Ideally I'd like to drop it to 2m, but since it's collecting some prometheus metrics I think is better to collect just a couple of more datapoints (30s each) to get a better data quality.
> 
> I see you mentioned 2m but I see the runtime is now 3m? Did you mean to say reduce it by 2m?

Ideally I'd like to drop it to 2m, but since it's collecting some prometheus metrics I think is better to collect a couple of more datapoints (30s each) to get a better data quality.

**Review by jtaleric — APPROVED** [review]
lgtm

**Pull request merged**
