### PR TITLE
improve the results file name

### PR DESCRIPTION
**Pull request by masco**
currently we need to identify/differenciate the file based on time only
adding workload name in the filename will help be more helpful

### CODE REVIEW

**Comment by masco** [comment]
@mohit-sheth did you see this useful?

**Comment by mohit-sheth** [comment]
hi @masco, sorry for the delayed reply
I remember having some issues with 
```
params.sheetname[0]}
```
Did you test it by any chance?

**Comment by masco** [comment]
hey @mohit-sheth, yeah tested in my env, even I am using this in my test env now also.
if you want I can share the env with you. you can have a look

**Comment by masco** [comment]
hey @mohit-sheth, yeah tested in my env, even I am using this in my test env now also.
if you want I can share the env with you. you can have a look

**Comment by Harshith-umesh** [comment]
closing since this fix is outdated.

**Pull request closed without merging**
