### PR TITLE
Netobserv perf tests

### PR DESCRIPTION
**Pull request by memodi**
### Description
Adding scripts for performance testing for network-observability.

### CODE REVIEW

**Comment by memodi** [comment]
/assign @mffiedler @kedark3 
could you help review this PR?

**Review by jtaleric — CHANGES_REQUESTED** [review]
if am reading the README, this is literally a wrapper, of a wrapper, of a wrapper? Is that correct?

**Comment by smalleni** [comment]
Can this be done as part of the existing networking e2e scripts by passing an additional flag or something to script?

**Comment by jtaleric** [comment]
> Can this be done as part of the existing networking e2e scripts by passing an additional flag or something to script?

Better yet, just maintain this outside of end to end?

**Comment by memodi** [comment]
> if am reading the README, this is literally a wrapper, of a wrapper, of a wrapper? Is that correct?

The intention wasn't to create a wrapper around networking e2e tests, but rather to **reuse** the existing code for networking e2e benchmarking tests and only adding changes required for network observability (netobserv) tests since both are tightly coupled.

**Comment by memodi** [comment]
> Can this be done as part of the existing networking e2e scripts by passing an additional flag or something to script?

I had thought about it and this was probably simplest solution I could think of without causing lots of code changes to existing networking scripts and by keeping additional code isolated for netobserv. It's basically calling the networking e2e scripts as is, the only change that is currently for networking is to call run_pod_network_test_fromgit.sh script with custom uperf for netobserv.

**Comment by kedark3** [comment]
@memodi your PR looks good to me, but since this is a community repo, we may want to get consensus on the code location and structure. If consensus is to maintain this outside of this repo, we can talk more about it on Slack. 

@jtaleric do we have an issue with adding network obsv tests in the repo? I think putting it in this repo makes is accessible to potentially any other teams or if there's a need for perfscale eng team(or other adjacent teams) then having it in this repo would make the most sense in terms of visibility, easy access. Putting it in OCP QE repos may not help in that regard.

**Comment by Harshith-umesh** [comment]
Closing after discussing this with @memodi, as e2e is not the best place for this code.

**Pull request closed without merging**
