### PR TITLE
uploaded initial ci test for ocs storage fio benchmark and artifacts …

### PR DESCRIPTION
**Pull request by acalhounRH**
…for Raw storage test.

### CODE REVIEW

**Comment by Harshith-umesh** [comment]
Can one of the admins verify this patch?

**Comment by jtaleric** [comment]
@acalhounRH  - who from the storage side should we ping to keep this moving forward?

**Comment by Harshith-umesh** [comment]
Hey @acalhounRH is this something we still want to pursue?

**Comment by acalhounRH** [comment]
Please follow up with Shekhar

**Comment by acalhounRH** [comment]
Recommend close, obsolete work item.

**Pull request closed without merging**
