### PR TITLE
fix path for yaml files; add ns arg for query

### PR DESCRIPTION
**Pull request by mohit-sheth**
compare.yaml files will be created in /network-perf instead of /network-perf/touchstone as we are installing touchstone with pip

### CODE REVIEW

**Review by jtaleric — APPROVED** [review]
LGTM

**Comment by rsevilla87** [comment]
Hey @mohit-sheth , this line also needs the -n flag
https://github.com/cloud-bulldozer/e2e-benchmarking/blob/fabd5cbbc24e5217978262e20718bf13ed1a9455/workloads/router-perf/run_router_test.sh#L45

**Review by rsevilla87 — CHANGES_REQUESTED** [review]
Added some comments

**Review by rsevilla87 — APPROVED** [review]
LGTM!

**Pull request merged**
