### PR TITLE
add apache v2 license

### PR DESCRIPTION
**Pull request by mohit-sheth**
Add License file

Description
This commit proposes an Apache v2 license. Need ack from all current contributors.

### CODE REVIEW

**Review by chaitanyaenr — APPROVED** [review]
LGTM

**Review by dry923 — APPROVED** [review]
LGTM!

**Review by paigerube14 — APPROVED** [review]
LGTM

**Review by smalleni — APPROVED** [review]

**Comment by jtaleric** [comment]
Thanks Mohit! LGTM!

**Review by afcollins — APPROVED** [review]
LGTM

**Review by mukrishn — APPROVED** [review]

**Review by morenod — APPROVED** [review]
LGTM

**Review by Harshith-umesh — APPROVED** [review]
LGTM

**Comment by venkataanil** [comment]
LGTM

**Review by venkataanil — APPROVED** [review]

**Review by rsevilla87 — APPROVED** [review]
LGTM

**Pull request merged**
