### PR TITLE
Provide prereqs for Python code for router-perf-v2

### LINKED ISSUE #140: Provide a requirements.txt for workload/router-perf-v2
workload and csv_gen use some uncommon pre-reqs.  Provide and document an easy way to install them to avoid a nasty surprise with csv_gen failing after a long run.

### PR DESCRIPTION
**Pull request by mffiedler**
Provide an easy way to install pre-reqs for workload.py and csv_gen.py.

Additionally, update csv_gen.py to not rely on system python3 in case user is running in a virtualenv

Fixes #140 

@rsevilla87 @mohit-sheth PTAL

### CODE REVIEW

**Comment by rsevilla87** [comment]
Maybe we can execute `pip install -r requirements.txt` from the code?

**Comment by mffiedler** [comment]
> Maybe we can execute `pip install -r requirements.txt` from the code?

Good idea,  I am thinking before deploy_infra.  Let me know if there is a better spot.  Will test that on a clean virtualenv and add a new commit.

**Comment by rsevilla87** [comment]
> > Maybe we can execute `pip install -r requirements.txt` from the code?
> 
> Good idea, I am thinking before deploy_infra. Let me know if there is a better spot. Will test that on a clean virtualenv and add a new commit.

Yeah, that would be a perfect spot.

**Comment by kedark3** [comment]
> > Maybe we can execute `pip install -r requirements.txt` from the code?
> 
> Good idea, I am thinking before deploy_infra. Let me know if there is a better spot. Will test that on a clean virtualenv and add a new commit.

if we put that in the code, wouldn't it also make sense to create an ephemeral virtualenv? We wouldn't want to try to install some pip packages on user's system, and likely to fail.

**Comment by mffiedler** [comment]
I think @kedark3 is correct.   Least surprise would be letting the end-user fulfill the pre-reqs themselves unless we want to get into the business of managing virtualenvs which we do not do for our other tools.

**Comment by rsevilla87** [comment]
We're already using venvs in other tools:

https://github.com/cloud-bulldozer/e2e-benchmarking/blob/bb226b0acbc2483e053528a14678d6a04ee0db3c/workloads/upgrade-perf/common.sh#L58-L60
https://github.com/cloud-bulldozer/e2e-benchmarking/blob/fe879cac4821ea569be8ee2cd7a70ccbfe428adb/utils/touchstone-compare/run_compare.sh#L7-L9

**Review by mohit-sheth — APPROVED** [review]
LGTM

**Review by rsevilla87 — APPROVED** [review]
LGTM

**Pull request merged**
