### PR TITLE
Updated compare.sh to use files warehoused in different locations

### PR DESCRIPTION
**Pull request by nathan-weinberg**
### Description
By default, comparison config files will be expected in `benchmark-comparison/config` directory - however, you can now also set the `CONFIG_LOC` env variable to a custom path to look for the config files as well

### Fixes
- Removes `netobserv_touchstone.json` file
- Updated `compare.sh` script

### CODE REVIEW

**Comment by paigerube14** [comment]
Do we want to take out the config files from this repo? There is a pr open for moving them in benchmark comparison

**Comment by nathan-weinberg** [comment]
Sure, can do in this one

**Review by jtaleric — APPROVED** [review]
lgtm, holding until hear from @paigerube14

**Review by paigerube14 — APPROVED** [review]
lgtm, helped Nathan work/talk through this and easily had successful runs in our jenkins jobs

**Pull request merged**
